### ISSUE TITLE
QuickStart example fails to build with latest version of OSO

### ISSUE THREAD

**Issue by delicb** [osohq/oso-go-quickstart#1]
On line https://github.com/osohq/oso-go-quickstart/blob/main/quickstart.go#L76 and the next one, build fails since the change introduced with contrustor support in Go (https://github.com/osohq/oso/commit/e02cac8186e9bc6bddc518faa7758162032669c1). 

I guess simple fix would be to provide `nil`, since example does not require constructor. 

I can send a pull request, if that is ok.

**Comment by dhatch** [comment]
Thanks for opening this @delicb ! Providing `nil` sounds like a good fix to me.

If you're interested in doing a PR we'd be happy to accept it!
